"""Typed-entity extraction over RAG paragraphs — Flair / OntoNotes 5.0.

Riprap moved off GLiNER (which trains on PILE-NER, a synthetic corpus
generated by GPT-3.5/4) to Flair fine-tuned on **OntoNotes 5.0** —
the Linguistic Data Consortium corpus annotated by trained linguists
at the Brandeis Annotators' Workshop. OntoNotes is the cleanest large
NER corpus there is: human-labeled, multi-genre, peer-reviewed, used
in thousands of academic papers.

This keeps the Riprap stack's governance story consistent: every
specialist ML model in the pipeline has either an enterprise-AI-
governance umbrella (IBM, NASA, ESA) or human-labeled public-domain
training data. No model in the stack was trained on closed-LLM-
generated synthetic data.

Output shape is identical to the previous GLiNER module so downstream
code in `app/reconcile.py` and the FSM doesn't need to change. The
five Riprap entity labels map onto OntoNotes types:

    nyc_location           ← GPE, LOC, FAC
    dollar_amount          ← MONEY
    date_range             ← DATE, TIME
    agency                 ← ORG, NORP
    infrastructure_project ← PRODUCT, EVENT, WORK_OF_ART, LAW
"""
from __future__ import annotations

import logging
import os
import re
from dataclasses import dataclass

log = logging.getLogger("riprap.entity_extract")

# Five Riprap-canonical entity labels (unchanged from the GLiNER era).
ENTITY_LABELS = [
    "nyc_location",
    "dollar_amount",
    "date_range",
    "agency",
    "infrastructure_project",
]

# OntoNotes 5.0 → Riprap label mapping. Multiple OntoNotes types may
# resolve to the same Riprap label.
ONTONOTES_TO_RIPRAP: dict[str, str] = {
    # Geo / place / facility — locations of interest in NYC
    "GPE":         "nyc_location",
    "LOC":         "nyc_location",
    "FAC":         "nyc_location",
    # Money
    "MONEY":       "dollar_amount",
    # Time / date
    "DATE":        "date_range",
    "TIME":        "date_range",
    # Organizations + nationalities/political groups
    "ORG":         "agency",
    "NORP":        "agency",
    # Named "things" — products, events, statutes, works
    "PRODUCT":     "infrastructure_project",
    "EVENT":       "infrastructure_project",
    "WORK_OF_ART": "infrastructure_project",
    "LAW":         "infrastructure_project",
}

DEFAULT_THRESHOLD = float(os.environ.get("RIPRAP_NER_THRESHOLD", "0.55"))
MODEL_NAME = os.environ.get(
    "RIPRAP_NER_MODEL",
    "flair/ner-english-ontonotes-fast",  # ~150 MB, ~50ms/doc on CPU
)
ENABLE = os.environ.get("RIPRAP_NER_ENABLE",
                        os.environ.get("RIPRAP_GLINER_ENABLE", "1")
                        ).lower() in ("1", "true", "yes")

_TAGGER = None  # lazy


@dataclass
class Extraction:
    label: str
    text: str
    score: float


def _ensure_tagger():
    """Lazy Flair tagger load. Returns None if disabled or load fails so
    callers can silently fall back to a no-op (preserves the contract
    the FSM step relied on with GLiNER)."""
    global _TAGGER
    if not ENABLE:
        return None
    if _TAGGER is not None:
        return _TAGGER
    try:
        from flair.models import SequenceTagger
        log.info("entity_extract: loading %s", MODEL_NAME)
        _TAGGER = SequenceTagger.load(MODEL_NAME)
    except Exception:
        log.exception("entity_extract: load failed; specialist will no-op")
        _TAGGER = False  # sentinel — falsy but distinct from None
    return _TAGGER or None


def warm():
    _ensure_tagger()


def _source_short(rag_doc_id: str) -> str:
    """`rag_comptroller` -> `comptroller`. Anything not prefixed `rag_`
    passes through unchanged."""
    return rag_doc_id[4:] if rag_doc_id.startswith("rag_") else rag_doc_id


def _flair_predict(text: str) -> list[Extraction]:
    """Single-text NER pass. Returns Riprap-labeled extractions."""
    from flair.data import Sentence
    tagger = _ensure_tagger()
    if tagger is None:
        return []
    sentence = Sentence(text)
    tagger.predict(sentence)
    out: list[Extraction] = []
    for span in sentence.get_spans("ner"):
        on_label = (span.tag or "").upper()
        riprap_label = ONTONOTES_TO_RIPRAP.get(on_label)
        if not riprap_label:
            continue
        out.append(Extraction(
            label=riprap_label,
            text=span.text,
            score=float(span.score),
        ))
    return out


# --- Regex augmentations -------------------------------------------------
# OntoNotes' MONEY catches `$5.6 million` and `$1,000` reliably but
# sometimes misses bare-figure phrases like "$2M" in shorthand reports.
# A light regex backstop keeps the dollar_amount surface tight.
_DOLLAR_RE = re.compile(
    r"\$\s?[\d,]+(?:\.\d+)?\s*(?:million|billion|thousand|k|m|b)?",
    re.IGNORECASE,
)
_FY_RE = re.compile(
    r"\b(?:FY|fiscal year|fiscal years?)\s+\d{2,4}(?:[-–]\d{2,4})?\b",
    re.IGNORECASE,
)


def _regex_augment(text: str) -> list[Extraction]:
    out: list[Extraction] = []
    for m in _DOLLAR_RE.finditer(text):
        out.append(Extraction(label="dollar_amount", text=m.group(0), score=1.0))
    for m in _FY_RE.finditer(text):
        out.append(Extraction(label="date_range", text=m.group(0), score=1.0))
    return out


def extract_for_chunk(text: str,
                      threshold: float = DEFAULT_THRESHOLD) -> list[Extraction]:
    """Run NER + regex backstops on a single chunk. Returns deduped
    extractions above the score threshold."""
    if not text:
        return []
    # v0.4.5-era remote-inference path: if the ML specialist service
    # is reachable, prefer it over local model load. The remote was
    # GLiNER-based; with the swap to Flair it's a no-op until the
    # remote is also migrated. Tolerate the remote returning nothing.
    try:
        from app import inference as _inf
        if _inf.remote_enabled():
            remote = _inf.gliner_extract(text, ENTITY_LABELS)
            if remote.get("ok"):
                # Remote already returns Riprap labels — pass through.
                return [
                    Extraction(label=e["label"], text=e["text"],
                               score=float(e.get("score", 0)))
                    for e in remote.get("entities", [])
                    if e.get("score", 0) >= threshold
                ]
    except Exception:
        # Remote path is best-effort; local Flair below is the canonical.
        pass

    ents = _flair_predict(text) + _regex_augment(text)
    return [e for e in ents if e.score >= threshold]


def extract_for_rag_hits(hits: list[dict],
                         threshold: float = DEFAULT_THRESHOLD,
                         max_hits: int = 3) -> dict[str, dict]:
    """Run NER on the top-`max_hits` RAG hits. Returns a dict keyed by
    short source id (e.g. "comptroller") with the structured payload
    that the FSM stores into state["gliner"] and that
    `reconcile.build_documents()` consumes.

    State key remains `gliner` for backward compatibility with
    downstream consumers (cardAdapter, reconciler citation chips,
    audit logs). The implementation underneath is Flair/OntoNotes;
    the name "gliner" is a historical artefact.
    """
    out: dict[str, dict] = {}
    if not hits:
        return out
    for h in hits[:max_hits]:
        source = _source_short(h.get("doc_id", "rag_unknown"))
        ents = extract_for_chunk(h.get("text", ""), threshold=threshold)
        if not ents:
            continue
        # Dedup verbatim repeats (common in agency PDFs that repeat
        # "DEP" 13 times in a methodology section).
        seen = set()
        deduped: list[Extraction] = []
        for e in ents:
            key = (e.label, e.text.lower())
            if key in seen:
                continue
            seen.add(key)
            deduped.append(e)
        out[source] = {
            "rag_doc_id": h.get("doc_id"),
            "title": h.get("title"),
            "paragraph_excerpt": h.get("text", "")[:240]
            + ("…" if len(h.get("text", "")) > 240 else ""),
            "n_entities": len(deduped),
            "entities": [{"label": e.label, "text": e.text,
                          "score": round(e.score, 3)} for e in deduped],
        }
    return out
