"""Legacy module name — kept as a backward-compat re-export shim.

The actual entity extraction now lives in
`app.context.entity_extract` and uses Flair fine-tuned on OntoNotes 5.0
(a human-labeled Linguistic Data Consortium corpus) rather than GLiNER
(which trained on PILE-NER — synthetic data generated by closed-weight
LLMs).

Downstream callers (`app.fsm.step_gliner`, `app.reconcile.build_documents`)
import from this module by name; rather than touch every call site, we
re-export the public surface here. The FSM state key remains `gliner`
for the same reason — it's a historical artefact, not a description of
the implementation.

See `docs/briefing-standards.md` and `app/context/entity_extract.py`
for the rationale and the new model lineage.
"""
# Keep the historical MODEL_NAME export available — some scripts log it.
from app.context.entity_extract import (  # noqa: F401
    DEFAULT_THRESHOLD,
    ENTITY_LABELS,
    MODEL_NAME,  # noqa: F401
    Extraction,
    extract_for_chunk,
    extract_for_rag_hits,
    warm,
)
